### ISSUE TITLE
About paper 'DeepStrip: High Resolution Boundary Refinement'

### ISSUE THREAD

**Issue by HuaZheLei** [pengzhou1108/GSRNet#5]
Hi, your work 'DeepStrip: High Resolution Boundary Refinement' is excellent. I'd like to know if code of the  paper will be open-sourced someday.

**Comment by pengzhou1108** [comment]
@HuaZheLei Thanks for your interest. We are still working on it and hopefully it will be released soon.

**Comment by HuaZheLei** [comment]
> @HuaZheLei Thanks for your interest. We are still working on it and hopefully it will be released soon.

Cool!

**Comment by rAm1n** [comment]
Hi there,

Any update on this? Are you still planning to release the code?

**Comment by pengzhou1108** [comment]
> Hi there,
> 
> Any update on this? Are you still planning to release the code?

Hi,

It seems we are  unable to release the code at this time according to the company's policy.  However, we will plan to release later once get approved.

**Comment by Davidsonson** [comment]
3 years later and I would also like to see this. Specifically the strip creation portion. I'm struggling to go from the contour to the 80x4096 high resolution strip.

**Comment by pengzhou1108** [comment]
> 3 years later and I would also like to see this. Specifically the strip creation portion. I'm struggling to go from the contour to the 80x4096 high resolution strip.

Sorry for the inconvenience. We were not able to release the code due to company policy.

**Comment by Davidsonson** [comment]
I understand. Can you at least tell me if you used an existing python
library to generate the B-spline or if it was entirely custom? I'm not able
to find anything that works with opencv or PIL so I am thinking it must
have been custom but wanted to ask.

**Comment by pengzhou1108** [comment]
> 

Sure, I used existing lib in scipy (from scipy import interpolate) to obtain the norm map of the contour (cv2.findContour)
